#define INPUT_DIMENSION 256
#define INSIDE_DIMENSION 512
#define NUM_HEADS 8
#define OUTPUT_DIMENSION INSIDE_DIMENSION/NUM_HEADS
#define FF_DIMENSION INSIDE_DIMENSION*8

// Modify the following definitions later
#define SQRT_DIMENSION 8
#define SQRT_DIMENSION_SHIFT 3